SourceForge upload script(s) unified, revised, improved.

diff --git a/tools/toSF b/tools/toSF
--- a/tools/toSF
+++ b/tools/toSF
@@ -1,45 +1,77 @@
 #! /bin/bash
 
-## This script uploads the web pages from this sandbox to the public web-site.
-## This action will make the current content live - please doublecheck changes
-## before upload!
-## The public web site is at http://smtcomp.sourceforge.net/
-## This script only does pages for a single year ($year)!!!
+#
+# See display_usage() below for user documentation.
+#
 
-## The script takes a single argument - the sourceforge username
-## The value of that argument will default to the value of $SOURCEFORGE_USERNAME
+# abort on error
+set -eu
+set -o pipefail
 
-## You will need to enter your sourceforge password at the prompt
+# function to display usage message
+display_usage() {
+    echo
+    echo "Usage: $0 USERNAME [DIRECTORY]"
+    echo
+    echo "This script uploads the web pages from the local smtcomp-web/ sandbox to the"
+    echo "public web site. This action will make the current content live - please"
+    echo "double-check changes before upload!"
+    echo
+    echo "The public web site is at http://smtcomp.sourceforge.net/"
+    echo
+    echo "USERNAME: your SourceForge username. (You will be asked to enter your"
+    echo "  SourceForge password at the prompt, unless you have configured SSH to use"
+    echo "  public-key authentication.)"
+    echo
+    echo "DIRECTORY: the sub-directory of smtcomp-web/ to upload (e.g., 2005). This"
+    echo "  directory must exist locally. If DIRECTORY is specified, it will be uploaded"
+    echo "  recursively, i.e., with all its subdirectories. If DIRECTORY is omitted, the"
+    echo "  top-level files in smtcomp-web/ will be uploaded instead (non-recursively)."
+    echo
+    echo "To prevent accidental data loss, files deleted in the sandbox are NOT deleted"
+    echo "from the web. Please use an SFTP client to delete web files manually."
+    echo
+}
 
-## NOTE: This script should copy all the web files; for some reason the
-## recursive copying did not work, so each subdirectory is explicitly listed.
-## NOTE ALSO: Files deleted in the source set are not deleted from the web
+# if less than one or more than two arguments were supplied, display usage
+if [[ $# -lt 1 || $# -gt 2 ]]; then
+    display_usage
+    exit 1
+fi
 
-username=$1
-year=2014
-if [ "$username" == "" ]; then username=$SOURCEFORGE_USERNAME ; fi
-if [ "$username" == "" ]; then echo Specify your sourceforge username either on the command line or by setting the environment variable SOURCEFORGE_USERNAME ; exit 1; fi
+# check whether user had supplied -h or --help; if yes, display usage
+if [[ "$1" = "-h" || "$1" = "--help" ]]; then
+    display_usage
+    exit 0
+fi
 
+USERNAME="$1"
 
-cd `dirname $0`/../smtcomp-web
+DIRECTORY=""
+if [[ $# -ge 2 ]]; then
+    DIRECTORY="$2"
+fi
 
+cd $(dirname "$0")/../smtcomp-web/
 
-sftp $username,smtcomp@web.sourceforge.net  << HERE
-put [a-z]* htdocs
-mkdir htdocs/$year
-cd htdocs/$year
-mkdir systemDescriptions
-lcd $year
-put * .
-cd reports
-lcd reports
-put * .
-put .htaccess .
-cd ../systemDescriptions
-lcd ../systemDescriptions
-put * .
-exit
+# if $DIRECTORY was specified
+if [[ -n "$DIRECTORY" ]]; then
+    # check whether $DIRECTORY exists
+    if [[ ! -d "$DIRECTORY" ]]; then
+        echo "Directory '$DIRECTORY' not found in ../smtcomp-web/."
+        exit 1
+    fi
+    # put $DIRECTORY (recursively)
+    sftp -b - "$USERNAME,smtcomp@web.sourceforge.net" << HERE
+cd htdocs
+put -r "$DIRECTORY"
+bye
 HERE
-
-
-
+else # no directory was specified
+    # put each file from .
+    sftp -b - "$USERNAME,smtcomp@web.sourceforge.net" << HERE
+cd htdocs
+$(find . -maxdepth 1 -type f -print0 | while read -d $'\0' FILE; do echo "put \"$FILE\""; done)
+bye
+HERE
+fi
